### ISSUE TITLE
Expired pre-trained model download link

### ISSUE THREAD

**Issue by yurimjeon1892** [shiyujiao/Boosting3DoFAccuracy#1]
Dear  Yujiao,

I read your research with interest and tried to reproduce the results. 

However, it seems that the download link for the pre-trained model has expired with this message: Sorry, the link has expired. The link was set to expire after a certain amount of time. Please contact the person who shared this link with you.

Could you please address this issue? Thank you.

Regards, Yurim.

**Comment by YujiaoShi** [comment]
Hi, sorry for the late reply. 

The model link has been updated, and will expire for one month again. I am sorry for the problem.

**Comment by yurimjeon1892** [comment]
Thanks for the reply!
